namespace OpenTibia.Server.Game.Networking;

// === CLIENT -> SERVER ===
public enum ClientOpcode : byte
{
    REQUEST_LOGIN = 1,
    REQUEST_LOGOUT = 2,

    MOVE_WEST = 3,
    MOVE_NORTH = 4,
    MOVE_EAST = 5,
    MOVE_SOUTH = 6,

    MOVE_NORTHWEST = 7,
    MOVE_NORTHEAST = 8,
    MOVE_SOUTHEAST = 9,
    MOVE_SOUTHWEST = 10,

    CLIENT_MESSAGE = 12,
    CLIENT_USE_TILE = 13,
    CLIENT_MOVE_ITEM = 16,

    CONTAINER_CLOSE = 17,
    CONTAINER_ITEM_USE = 20,

    PLAYER_TURN = 22,
    MOVE_ITEM_ALL = 23,
    CAST_SPELL = 24,

    JOIN_CHANNEL = 25,
    SEND_PRIVATE_MESSAGE = 26,
    TARGET_CREATURE = 27,
    CHANGE_OUTFIT = 28,
    LOOK_AT = 29,

    ITEM_USE_WITH = 30,
    ITEM_USE_ALL = 31,
    ITEM_LOOK_ALL = 32,

    TARGET_CANCEL = 33,
    REMOVE_FRIEND = 34,
    ADD_FRIEND = 35,
    LEAVE_CHANNEL = 36,

    BUY_OFFER = 37,
    OPEN_KEYRING = 38,

    LATENCY = 255
}

// === SERVER -> CLIENT ===
public enum ServerOpcode : byte
{
    ITEM_ADD = 1,
    WRITE_CHUNK = 2,
    ENTITY_SPAWN = 3,
    SERVER_MESSAGE = 4,
    CREATURE_MESSAGE = 5,

    DECREASE_HEALTH = 6,
    ENTITY_MOVE = 7,
    OPEN_CONTAINER = 8,
    CONTAINER_ITEM_ADD = 9,

    LOGIN_SUCCESS = 10,

    ENTITY_REMOVE = 11,
    ITEM_REMOVE = 12,

    CREATURE_TURN = 14,
    CONTAINER_CLOSE = 15,
    CREATURE_INFO = 16,
    CONTAINER_ITEM_REMOVE = 17,

    SEND_MAGIC_EFFECT = 18,
    GAIN_EXPERIENCE = 19,

    PLAYER_EQUIP_ITEM = 20,
    PLAYER_UNEQUIP_ITEM = 21,

    INCREASE_HEALTH = 22,
    JOIN_CHANNEL = 23,
    CREATURE_TELEPORT = 24,
    SEND_PRIVATE_MESSAGE = 25,
    LEVEL_ADVANCE = 26,

    JOIN_PRIVATE_CHANNEL = 27,
    PLAYER_LOGIN = 28,
    PLAYER_LOGOUT = 29,

    PROPERTY_CHANGE = 30,
    SEND_SERVER_DATA = 32,
    CHANGE_OUTFIT = 33,
    ITEM_INFORMATION = 34,
    CANCEL_MESSAGE = 35,
    TRANSFORM_ITEM = 36,

    SEND_DISTANCE_MAGIC_EFFECT = 37,

    FRIEND_STATUS = 39,
    REMOVE_FRIEND = 40,
    ADD_FRIEND = 41,

    CREATURE_SAY = 42,
    READ_TEXT = 43,
    CHARACTER_INFORMATION = 44,
    ENTER_ZONE = 45,
    ADD_ACHIEVEMENT = 46,
    TRADE_OFFER = 47,
    WORLD_TIME = 48,
    PLAYER_STATISTICS = 49,
    COMBAT_LOCK = 50,

    SERVER_ERROR = 51,
    CAST_SPELL = 52,
    WRITE_EMOTE = 53,
    TOGGLE_CONDITION = 54,
    SET_TARGET = 55,
    WRITE_SPELLS = 56,

    INCREASE_MANA = 57,
    DECREASE_MANA = 58,

    LATENCY = 255
}